### PR TITLE
Change file hook handler to callback function, rename to hook_require

### PR DESCRIPTION
**Pull request by Aussiemon**
This commit removes the function hook part of hook_file and turns it into a callback execution instead. Regular hooks can still be applied through the callback, but it now also allows modifying non-function values.

EDIT: hook_file is now renamed to hook_require

### CODE REVIEW

**Comment by sclu1034** [comment]
Maybe call it `mod:on_require` to differentiate it from hooks, which are usually done on functions?

**Comment by fracticality** [comment]
`mod:on_require`, at least to me, gives the impression that it's the callback handler for an event propagated by DMF.
Perhaps `mod:require_callback` or even `mod:register_require_callback`?

**Comment by sclu1034** [comment]
> Perhaps `mod:require_callback` or even `mod:register_require_callback`?

With that name, I would expect that value to _be_ the callback function, e.g. `some_async_function(..., mod.require_callback)`.

I guess `mod:hook_require` would also work, as this is essentially what it does, and what people should use instead of `mod:hook(_G, "require")`.

**Comment by fracticality** [comment]
> I guess `mod:hook_require` would also work, as this is essentially what it does, and what people should use instead of `mod:hook(_G, "require")`.

That's fair.
`mod:hook_require` seems enough to me.

**Comment by fracticality** [comment]
[Line 433](https://github.com/Darktide-Mod-Framework/Darktide-Mod-Framework/pull/5/commits/f645473f31164755057934d299968b4fc34949c7#diff-abb403f2cff7eb94ede287bc6cd43231bd7ce0326daddf099341d0cd2612eabbR433) doesn't work as expected if more than one mod hooks the same file (the `[mod_name] = {}` initialization is skipped).

Recommend conversion to:
`_file_hooks_applied_to_file[obj_str]           = _file_hooks_applied_to_file[obj_str] or {}
    _file_hooks_applied_to_file[obj_str][mod_name] = _file_hooks_applied_to_file[obj_str][mod_name] or {}`

**Comment by Aussiemon** [comment]
> [Line 433](https://github.com/Darktide-Mod-Framework/Darktide-Mod-Framework/pull/5/commits/f645473f31164755057934d299968b4fc34949c7#diff-abb403f2cff7eb94ede287bc6cd43231bd7ce0326daddf099341d0cd2612eabbR433) doesn't work as expected if more than one mod hooks the same file (the `[mod_name] = {}` initialization is skipped).
> 
> Recommend conversion to: `_file_hooks_applied_to_file[obj_str] = _file_hooks_applied_to_file[obj_str] or {} _file_hooks_applied_to_file[obj_str][mod_name] = _file_hooks_applied_to_file[obj_str][mod_name] or {}`

Good catch!

**Comment by Aussiemon** [comment]
I've made the suggested changes to hook_require and fixed the initialization bug

**Pull request merged**
